apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian
  template:
    metadata:
      labels:
        app: debian
    spec:
      containers:
      - name: pg-tpcc
        image: debian-postgres:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5432

